name: liLO
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.5.0+6

environment:
  sdk: ">=2.9.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^2.5.0
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
